# -*- coding: utf-8 -*-
"""Clase 2 Listas y Tuplas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jnSgavDFfY1NRhDkCW856JkqIcZ3ScTl
"""

[24, 12, "Hola mi dato", 14, 18]

type ([25, 30, 45, "mi lista "])

print(list)

cadena ='esta es una cadena de prueba'
print(cadena)

lista = [5+ 5+ 10+ 7]
print(lista)

lista = [5,5,10]
lista_concatenada = lista + [cadena, 5510]
print(lista_concatenada)

lista1 = ("esta es mi primera lista", [5,10,15,20])
print(lista1)

lista = [1,2,3,4]
print(lista)
lista= []
print(lista)

lista = [1,3,5,6]
lista.append("otro valor")
print(lista)

lista = [5,6,7,8,9]
lista.pop()
print(lista)

lista = [1,3,5,6,7,8,9,10,11]
lista.count
print(lista)
print(lista.count(6))

tuplas_heterogeneas = [1,2,3,4,5,6]
tupla = 2,4,6,8
print(tuplas_heterogeneas)
lista = ["esta es una lista"]
print(lista)
print(type(lista))
print(type(tupla))

tupla = ()
tupla = tuple()
print(tuple('ricardo'))

primer_tupla = (5,20,30)
tupla = ("esto, es ,una ,tupla"), ("otra ,tupla")
tupla[-2]
print(tupla)
print(primer_tupla[-2])