# -*- coding: utf-8 -*-
"""Ejercicio Python- Coderhouse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTb5XDxAZahU-no3kTPEpoteVxDTHnlj
"""

print("hola mundo, coderhouse")

print(50 +5)

print(type(15 +5))

print(8/2)

print('hola amigos bienvenidos a python')

print(type('estoy aprendiendo python')) #comentario

print("hola mundo, mi primera linea de codigo en python")

print("C:/juanjose/archivos")

print(r"C:/juanjose/archivos")

texto= "palabra  nueva"
print(type({5+1}) )

print(f"Mi nueva casa esta a {5+10} km de distancia de la tuya")

print(""" una cadena
otra cadena más""")

mi_variable = 2
mi_variable

fecha_de_nacimiento = "19 de Enero 1997"
fecha_de_nacimiento

nombre = input("Hola mundo")

nombre = input("¿Cómo te llamas?")

nombre = int(input("¡Dime tu edad!"))

print(5*5)

cadena = "Python"
cadena * 2

nombre =input("escribe algo")